### ISSUE TITLE
Snippets don't work between tags

### ISSUE THREAD

**Issue by simonc** [victorlcampos/phoenix-snippets#1]
Hi :)

I just installed your package and it's working fine except for a small issue.
When the cursor is right between tags like

``` html
<li>|</li>
```

the snippet is not used and it just prints an `=` sign

``` html
<li>= |</li>
```

Just wanted to let you know :wink:

**Comment by victorlcampos** [comment]
Hi @simonc, thx.
I will study more about atom packeges and will try to fix it.

Do you have some idea?

**Comment by simonc** [comment]
@victorlcampos sadly no, I'm playing with Atom from time to time but it's not my day-to-day editor, I don't know how it works in that kind of case. Maybe a different scope is provided in this situation compared to when you're on a separate line. Sorry I couldn't be more useful :disappointed:
